### ISSUE TITLE
In google sheet, the Protected Sheets & Ranges should be disabled

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#10]
Disable all Protected sheets & ranges. (@Lacey-boop and @unity1979 were previously locked out)

Brief Instructions:
1. On spreadsheet, click Data -> click Protected sheets & Ranges:
![image](https://user-images.githubusercontent.com/70724023/94497065-ebf98b00-01aa-11eb-8d93-2411a902e2dd.png)

2. Click each protected element:
![image](https://user-images.githubusercontent.com/70724023/94497162-3418ad80-01ab-11eb-83d5-7cb2b6ca3df3.png)

3. Click 🗑 (trash icon) -> Remove (for each):
![image](https://user-images.githubusercontent.com/70724023/94497284-95d91780-01ab-11eb-8d3a-d4241f91dd63.png)
🙏

**Comment by ctwilkie** [comment]
Done!

**Comment by unity1979** [comment]
The friend speaks my mind. This is done and thank you.
