### ISSUE TITLE
Resize [Timezone] tabs for best horizontal fit (for printing)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#11]
There are excess columns on the right side of the [Timezone] tabs. Suggestion to delete those columns

**Comment by unity1979** [comment]
Fixed, closing 🙏
![image](https://user-images.githubusercontent.com/70724023/94598640-164b5700-0244-11eb-810d-86a62b05e2ad.png)

**Comment by KrisRecoveryDharma** [comment]
Just to clarify and confirm: the core issue was that the document was not
printer-friendly because the last column did not fit on the page.  It looks
like that is the problem that you solved.  Jut want to make sure.
Thanks!
Kris

**Comment by unity1979** [comment]
(yes this was for addressing the printer-friendly problem! also this comment is for testing github subscription.)
