### ISSUE TITLE
Newly Linked time Zone tabs are not showing day and time

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Meetings#15]
https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1567715471&single=true

We received a notice that the time and date for Mountain Time tab are not showing up. 
I just checked the page.  When I go to the original link, they show up fine.  when I go to the new links, less than half of tab pages are showing the time. 

Needs: 
1. Revert to previous version or fix the script
2. Review the other tabs to ensure that they are working.

Thank you, fabulous Meeting List Team!

Kris

**Comment by unity1979** [comment]
Bug is intermittent, if refreshed once or twice it will properly display.  This is for all pages. this is reported as bug #14 

For me it loaded as this:
![image](https://user-images.githubusercontent.com/70724023/94772106-bc46b080-036d-11eb-8d31-ded9740c13a8.png)

But if you refresh it sometimes it displays this garbage as "#NAME?"
![image](https://user-images.githubusercontent.com/70724023/94772295-252e2880-036e-11eb-9d33-dd25e9897edf.png)

**Comment by unity1979** [comment]
I recommend we revert to previous version for now until we find a fix

**Comment by KrisRecoveryDharma** [comment]
I just checked it and most of them did not work for me. 
![image](https://user-images.githubusercontent.com/70176719/94772534-d7261e80-0387-11eb-8af4-684e9e72e3e0.png)

**Comment by KrisRecoveryDharma** [comment]
Gremlins!!!!

**Comment by KrisRecoveryDharma** [comment]
I sent the link to the original spreadsheet to the list.

**Comment by unity1979** [comment]
Possible quickfix: There is a problem on the Protected & Hidden sheet "Zone". 
Column C makes calls to a function called TimeZoneOffset, which sometimes incurs Loading time resulting in a "Loading..." for the values we need.  

We can fix this if we have access to editing [Zone] tab and hardcode the values for now.
![image](https://user-images.githubusercontent.com/70724023/94777715-c7530e00-0378-11eb-87ab-b7508fada445.png)

**Comment by unity1979** [comment]
Requesting edit rights for [zone] tab. Currently it is still locked to View Only. Here is a comment on why the bug is happening and how anyone with edit rights to [zone] tab can fix it 👍 

![image](https://user-images.githubusercontent.com/70724023/94835993-48d18d00-03c7-11eb-9320-b1d1b77b5870.png)

**Comment by unity1979** [comment]
Alternatively, if someone has editing rights (@KrisRecoveryDharma), if you could paste these constant values into Column C, we can close this issue and move forward

Paste these into column C of [Zone]
--
0.4166666667
0.4166666667
0.04166666667
-0.2083333333
0.08333333333
-0.1666666667
-0.1666666667
0.04166666667
-0.4166666667
0.375
-0.25
0.2395833333
-0.125
0.5416666667
-0.2916666667

**Comment by unity1979** [comment]
I have pasted hard-coded values.  This is fixed from what I am seeing. Can others verify and then close?

![image](https://user-images.githubusercontent.com/70724023/94840393-36f2e880-03cd-11eb-8763-0d5a5b2decec.png)

**Comment by ctwilkie** [comment]
you should be able to edit now, I removed the protected range.

**Comment by ctwilkie** [comment]
is it fixed b/c I reverted back a version?

**Comment by unity1979** [comment]
> is it fixed b/c I reverted back a version?

No it's fixed because I entered hardcoded values, instead of trying to compute the value 0.416666 about a million times every day :)  But also your revert helped fix other things!

**Comment by unity1979** [comment]
Fixed, closing issue. Go team!
