### ISSUE TITLE
Remove Protected Range for tab [Online UTC] (or enable editing for Thomas)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#17]
There is an error in the way that Online UTC determines whether the meeting is Online. 

Currently it is pulling from column B.  We need to replace this with E, "How is this meeting happening?"

**Comment by KrisRecoveryDharma** [comment]
Thank you for attending to this.  Though, there are a few adjustments. 

I do not see the error. Everything seems to be pulling okay. Can you pinpoint the error? 
Column B is central to the script. It is, in fact the central pivot. It provides the Offset Calculation. 
Column E (not G)  is the "How is this meeting happening"  that is also involved in the script.  It appears to be working.  What is the error? 
Thanks,
Kris

**Comment by unity1979** [comment]
Ooops yes you're right I'm tripping about Column G, it is Column E. let me update.

**Comment by unity1979** [comment]
If you look at the Unsorted equation below, you will notice that it is checking for "Online" in Column B.  However, in our questionairre, that's not where we ask about the Online/Inperson status.  Column B we ask for these 3 questions:

- Add a new meeting
- Change an existing meeting
- Cancel a meeting

(I hacked a temp hotfix and renamed them to "Add new Online" and "Change Online" and "Cancel Online" just so that the spreadsheets would not show up empty)

![image](https://user-images.githubusercontent.com/70724023/95621754-13f8b200-0a27-11eb-8eda-3539269a826b.png)

**Comment by unity1979** [comment]
If we were to re-enter the equation as follows, it would work properly for new entries:

=sort(filter('(unsorted)'!$C$3:$R,iferror(search("online",'(unsorted)'!$E$3:$E)>=0,false),iferror(search("yes",'(unsorted)'!$L$3:$L)>=0,false)),2,true)

**Comment by unity1979** [comment]
This is what happens if I didn't replace "Add a new meeting" with "Add a new meeting ONLINE".  
1) The Online UTC becomes blank
2) All timezones become blank

Feel free to verify by clicking on this spreadsheet here:
https://docs.google.com/spreadsheets/d/1GGb5S7OyFpM1L7Vsdp4FPBz-qYZ_W6HPM_xFVLpt4Q4/edit#gid=1720303593

![image](https://user-images.githubusercontent.com/70724023/95634781-8a091300-0a3f-11eb-8245-3c586ca9abc0.png)

**Comment by unity1979** [comment]
Craig removed protection as requested. Thanks
