### ISSUE TITLE
Fix filtering for searching on [Online UTC] tab to read from appropriate column

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#18]
There is an error in the way that Online UTC determines whether the meeting is Online.

Currently it is pulling from column B. We need to replace this with G, "How is this meeting happening?"

**Comment by KrisRecoveryDharma** [comment]
I think this is  duplicate of #17 issue. 
Thanks,
Kris

**Comment by unity1979** [comment]
It was on purpose, I was perhaps incorrectly assuming that we would resolve the problem by granting me access to the Online UTC tab. 

Access would *greatly* improve speed and aid the meeting list in future similar changes (such as adding columns for Zoom ID and Dial-In info)   For me, being locked out of the Online UTC slows things down tremendously.  It forces me to have to think of work-arounds instead of addressing the actual problem. **Basically creates additional unnecessary dukkha!** 👍

**Comment by unity1979** [comment]
I have Implemented as requested. Closing bug
