### ISSUE TITLE
RDG meeting list: Should include simple call-in details

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#2]
• so people know they can call in to these meetings
• we just need to tell them the Meeting ID and the same call-in info as follows:

```
Meeting ID: (Can be pulled from zoomlink)

Dial by your location
        +1 669 900 6833 US (San Jose)
        +1 346 248 7799 US (Houston)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Germantown)
        +1 312 626 6799 US (Chicago)
        +1 646 558 8656 US (New York)
(Or find your local number: https://zoom.us/u/1XAMm )
```

**Comment by unity1979** [comment]
Thoughts? Perhaps wait to discuss at meeting?

**Comment by KrisRecoveryDharma** [comment]
Yes, that is the kind of thing that we will be able to include on the new
database, and also on the new Getting Started Beginners Guide.

Kris

**Comment by unity1979** [comment]
I'm thinking we can add this to the SiteMap temporarily. And offer this info:
1) When instructed, enter the zoom ID meeting number and password.
2) If you are unsure of the zoom ID meeting number, please email the meeting's contact. Ask them for the Meeting ID and Password for the time/day in question.

**Comment by KrisRecoveryDharma** [comment]
Lacey also wants to see this happen.   I think there are at least 3 different ways to solve this problem. We should have a zoom meeting soon to discuss the options.   She cannot attend the meeting on Friday at 6 pm.  perhaps we can schedule a meeting this weekend or on monday.

**Comment by KrisRecoveryDharma** [comment]
Confused about adding to the site map. I'm not sure what that means. I know what a site map is. But that is not the language I am familiar with for adding.  Where would it show up to give people the direction?

**Comment by unity1979** [comment]
(A) On the [sitemap] tab, I imagine it just has make-shift temporary instructions, since it's sort of a global "help/faq" type page. I'm totally open to other suggestions. 

![image](https://user-images.githubusercontent.com/70724023/93559866-9369f880-f935-11ea-97d1-9a317443eeea.png)

Possible other suggestion: (B) a Column for a URL for each meeting in the spreadsheet. It somehow has instructions for dial-in. Example: 

![image](https://user-images.githubusercontent.com/70724023/93560165-61a56180-f936-11ea-84b2-60c695b4e907.png)

For both (A) and (B) the callers would need a separate column clearly noting the Zoom Meeting ID #

**Comment by KrisRecoveryDharma** [comment]
Move this issue over to the other, newer issue:  Update Google Form.
