### ISSUE TITLE
Remove  meeting from list

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Meetings#23]
This meeting needs to be removed from the list.  I have gone ahead and marked that it is not open to the public, hoping that will remove it from the tabs. 

Add new | 2020-04-01 21:18 | Thursday 7:30 PM | Yes | Online | Thursday | 1:30 PM | CDT |   | St Louis, Missouri, USA | https://www.surveymonkey.com/r/T6KTVCM |   |   | Mettamay4you@gmail.com

It is currently listed at #162 on the unsorted page
https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?fbclid=IwAR3S9VWQhc7xX1gd2KaXsk-ILX0a_Q1Blki-uP-AF7IAKdRYAkxMcW6WcgI#gid=1720303593

The link for the meeting goes to a commercial page, which is inconsistent with the core intentions of the organization.  

I will accept volunteers to reach out to the meeting organizer to explain and to offer alternatives.  However, I can do it if no one else is available or feels clear about the organization's policies. 

Sorry for the shortness, Townhall was wonderful, but I am just not at 8:14 being able to get to this task after getting off the zoom. M creativity brain is lagging.  

Thank you all for your presence, it was wonderful because of your participation!

Kris

**Comment by unity1979** [comment]
Meeting has been removed!  

@KrisRecoveryDharma if you can write here why
1) it is inconsistent w core intentions
2) what their alternatives are,
it would greatly help me understand and I could draft the email.

**Comment by KrisRecoveryDharma** [comment]
There were a few reasons.

The email went to a company website. In addition to our not affiliating
with businesses, it appeared that the meeting was not facilitated by peers,
but by the owner of the business.  We do not have the power or desire to
restrain others organizations from using our materials, but we do not list
those meeting on our site.  The same would b etrue for a treatment center.
If the meeting was run by peers, then we would list it, but if it were run
by the therapist or other staff member then we would not.

I am happy to reach out to her to explain it as well.

Thank you!

Kris

**Comment by KrisRecoveryDharma** [comment]
If she can demonstrate that it is a peer-led meeting, then it can go back
up, but it would need to not be connected to a business. Peer-led does not
just mean that she is also in recovery. It means that it is not an aspect
of her business. We are quite adamant about that, given our recent birth
history.

Thanks again,

Kris

**Comment by unity1979** [comment]
@KrisRecoveryDharma Your input is clearly thought out with skillfulness.  If you're happy to, please reach out to her to explain these details?  I'm so glad you caught this, how did you hear about it?  I've seen this meeting before but didn't think twice

**Comment by KrisRecoveryDharma** [comment]
Thanks Somene brought it to my attention.

**Comment by unity1979** [comment]
> I am happy to reach out to her to explain it as well. Thank you! Kris
> […](#)

@KrisRecoveryDharma Did you write her? (so we can close out this bug! :) ) Thank you

**Comment by KrisRecoveryDharma** [comment]
I will try to get to it tomorrow afternoon.
Thank you!
Kris

**Comment by unity1979** [comment]
The meeting was removed, thanks all!
