### ISSUE TITLE
Holiday Schedule

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Meetings#24]
Work with joel@recoverydharma.org to develop a list of meetings that are meeting on during the new year holiday.  

Start with the regularly scheduled meetings to confirm by reaching out by email to the emails of the meeting facilitators for regularly scheduled meetings. 

Also reach out to the general community to ask if there will be any specially scheduled meetings. 

Next year, our calendar will be able to accommodate an automatic update of this schedule. For this year, though, there have been request and there is a need to coordinate and publish the information.

**Comment by unity1979** [comment]
This was completed, thanks all
