### ISSUE TITLE
Meetings list is out of order (not sorted by GMT, so it's unusable)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#28]
When in List View, the events are out of order. They're sorted by their own local time zone (instead of based on GMT.) 

For example, see in blue: 10:30am, 10:00am, 9:00am
![image](https://user-images.githubusercontent.com/70724023/153426956-057fc44d-5ad0-4cf9-a924-38ee250b45c6.png)

Expected behavior:
They should be sorted by GMT

**Comment by nutjob4life** [comment]
Asked contractor

**Comment by unity1979** [comment]
Great! 

(btw IMHO, this shouldn't cost anything extra, if they attempt invoice you: 

This is clearly an internationalization bug. Internationalization bugs arise sooner or later. Reporting this bug sooner helps them fix this bug sooner and prevent all future troubles for them, us, everyone.)

**Comment by unity1979** [comment]
Closing due to meeting list overhaul
