### ISSUE TITLE
Some meetings last multiple hours or days

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#29]
Some events are spanning multiple hours, or whole days:

![image](https://user-images.githubusercontent.com/70724023/153427554-fd83ad48-cdc4-472d-ade4-161712eb298c.png)

Expected behavior:
These events should last 60-90 minutes

**Comment by unity1979** [comment]
Peaceful Harmony with food meditation sangha seems to be a major one with: 
Duration: **11 months**
Repeating: **Weekly**

Example:
![image](https://user-images.githubusercontent.com/70724023/153428223-9b028dc8-78da-44a4-b34a-cc5f74c1fcb6.png)
![image](https://user-images.githubusercontent.com/70724023/153428333-ad87bb62-156d-485a-bcf7-c387fad44db7.png)

**Comment by nutjob4life** [comment]
Thanks @unity1979; I fixed Peaceful Harmony and Ann Arbor.

If you notice any others, please re-open and link 'em here in a comment
