### ISSUE TITLE
Glitch on In Person Meetings Page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Meetings#3]
The meeting time for San Antonio is showing up with the UTC time offset rather than the local meeting time. The row is also highlighted.  I'm not sure what the scripts are on this page, so I can't fix.  I checked to make sure their listing in the Unsorted List is correct.   The glitch will need to be addressed by Thom. 

https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?fbclid=IwAR3S9VWQhc7xX1gd2KaXsk-ILX0a_Q1Blki-uP-AF7IAKdRYAkxMcW6WcgI#gid=1492891510

Thanks!

Kris

**Comment by ctwilkie** [comment]
I got the time fixed.

**Comment by unity1979** [comment]
I got the highlighting oddities fixed as well 👍 The cells were set to conditional highlighting.
