### ISSUE TITLE
-Some Hybrid/Online events don't show the Orange label "[Virtual Event]"

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#30]
After selecting: 
https://recovery-dharma.flywheelsites.com/meetings/find-a-meeting/
List View → (Options Icon) → click Type → click Hybrid

Notice: Some Hybrid events are missing the orange label. Other events only display "Virtual Event".  
![image](https://user-images.githubusercontent.com/70724023/153429403-6853201b-23c6-4ac2-be80-0730d7524ddb.png)

Expected behavior:
They should display Orange label "Virtual/Physical Event"

**Comment by unity1979** [comment]
SIDE NOTE OF GOOD NEWS:
Only took 3 seconds to load this hybrid list! :)

**Comment by nutjob4life** [comment]
Julia Hayes entered the data for multiple "Spokane Sangha RD" meetings. For 3 of them, though, they selected "in person" as the "event attendance mode". "In person" doesn't prompt for online meeting information and does not get an orange label—even if they also selected "hybrid" as the "type".

(All the more reason to dump "hybrid".)
