### ISSUE TITLE
When meeting filter is set to Online meetings, Hybrid meetings don't appear

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#31]
After selecting:
https://recovery-dharma.flywheelsites.com/meetings/find-a-meeting/
List View → (Options Icon) → click Type → click Online

Notice: No Hybrid events are shown in the list.

Expected behavior:
Hybrid events should also be listed for Online filters

**Comment by nutjob4life** [comment]
I'm thinking we should just drop "Hybrid".

After all, you can check both "Online" and "In Person", so having a third option is redundant—and doesn't work! 😝

What do folks think?

**Comment by unity1979** [comment]
@nutjob4life I thought about this and thought of all the ways this actually makes a lot of good sense in my opinion. I like. 

Above all, I appreciate when confusing words are avoided when possible—“hybrid” is a term that often needs explanation. In-person and Online don’t.

+1 to remove hybrid 
(Subtask if approved: all existing “hybrids” should instead be checked both inperson and online)

**Comment by KrisRecoveryDharma** [comment]
Agree

**Comment by unity1979** [comment]
Closing due to overhaul. If this is an issue again we can reopen
