### ISSUE TITLE
Reveal Local Times for meetings (they're hidden until onClick)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#32]
Usability Bug & Feature request:
In List View, each meeting time is Hidden. User must click on "View in my time" to reveal when the meeting happens.

Steps to reproduce: 
https://recovery-dharma.flywheelsites.com/meetings/find-a-meeting/
Click List View

Notice "View in my time" is not revealed. 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/70724023/153482323-a2480704-4d54-419a-b560-55a8feb07d79.png">

Expected behavior:
"View in my time" should always be revealed by default. (Mentally computing time zones for meetings list, unfortunately, results in a very difficult user experience)

**Comment by nutjob4life** [comment]
Passed onto the contractor. I know they worked long and hard on that feature, and having it trigger by an `onClick` event was a compromise to get it to happen.

I agree, though, that it'd be better if it were just "always on". Hopefully they can do that and they don't charge too much.

**Comment by KrisRecoveryDharma** [comment]
This is where we are running into the limits of out of the box.

**Comment by unity1979** [comment]
Closing due to overhaul. If this is an issue again we can reopen
