### ISSUE TITLE
Request: Can we add Weekday? (Mon Tue Wed Thu Fri Sat Sun) to meeting list

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#33]
Meeting list does not show weekday information when displaying data.

Steps to reproduce:
Go to: https://recovery-dharma.flywheelsites.com/meetings/find-a-meeting/
Click: List View
Notice: Weekday is not presented

Ideal Behavior:
Indicates day of week along with date
![image](https://user-images.githubusercontent.com/70724023/153649200-0ac9b5db-f709-4d26-b490-812f49792406.png)

**Comment by nutjob4life** [comment]
Passed request onto contractor

**Comment by unity1979** [comment]
Nice. And If it takes too long we might apply a “workaround” fix where every meeting Name is prepended with a Weekday string (whether brute forced or programmatically)

**Comment by nutjob4life** [comment]
Especially if they charge a lot for it. We can save some 💸  by sitting down and putting in day of the weeks ourselves. It'll be annoying for some 200 meetings but it can be done.

**Comment by unity1979** [comment]
Closing due to meeting list overhaul
