### ISSUE TITLE
-Affinity: Non-BIPOC meetings show up in BIPOC filter (same for: LGBTQIA+, Gender Expansive, Men, Women)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#34]
To reproduce:
https://recovery-dharma.flywheelsites.com/meetings/find-a-meeting/
List View → Filter → Affinity → Women

Expected: I would expect a meeting list where it's Women/trans/NB only. 

Notice: Organizers have selected Women, but also many or all other affinities, including Men.

Notice: These meetings also have elected many/all other affinities:
- BIPOC
- Gender Expansive
- LGBTQIA+
- Men
- Other
- Women

The meetings are below. All affinities should be removed from these meetings.
1. On The "Isms"
2. No Mud No Lotus Group
3. LHSC RD
4. MZMC MD
5. Littlehampton RD MEETING
6. Socal Inner Peace Sangha Virtual Meeting 
7. Twin Cities Wednesday
8. Shambala RD

![image](https://user-images.githubusercontent.com/70724023/153690385-0d31e312-c82c-441a-8203-52b6860ba144.png)

**Comment by unity1979** [comment]
The same bug applies these affinities:

1. LGBTQIA
2. Gender Expansive
3. Men
4. Women

**Comment by nutjob4life** [comment]
Wow those screenshots are _hard to read_. 

But I don't get it. [From the meetings page](https://recovery-dharma.flywheelsites.com/meetings/find-a-meeting/) I do

1. List View
2. Filter (triple 🎚️  button)
3. Click AFFINITY
4. Click BIPOC (and be super patient)

and I get a list of meetings that all mention BIPOC. Isn't that correct?

**Comment by unity1979** [comment]
You're correct. I'll try to reiterate and update the bug, and also restate it here in this comment. (and I'll try to have better screenshots!)

(I've updated the bug and screenshot)

**Comment by unity1979** [comment]
We may need to adjust the language of the text to replace "Select the Affinity Category" 
![image](https://user-images.githubusercontent.com/70724023/153691233-5c66909c-428e-4afd-9218-74caaed377af.png)

Perhaps: "For Affinity Meetings Only. (Skip this, if you are unsure!) Select the Affinity self-identification to attend meeting."

**Comment by KrisRecoveryDharma** [comment]
Perhaps adding that it is a closed is that it is a closed meeting?

OK, I am leaning in the direction of changing the instructions

**Comment by unity1979** [comment]
Ok changing the instructions does meet these needs!

**Proposed Solution:**
1. Rename string from "Select Affinity Category" → “(Skip this, for meetings Open to All) For Closed meetings ONLY: choose Affinity self-identification requirement(s)”
2. Rename affinity type "Men" to "Men and Non-Binary" (inherently trans-inclusive)
3. Rename affinity type "Women" to "Women and Non-Binary" (inherently trans-inclusive)
4. Add new Affinity type: "Allies"
5. Remove all affinities from these meetings: On The "Isms" // No Mud No Lotus Group // LHSC RD // MZMC MD // Littlehampton RD MEETING // Socal Inner Peace Sangha Virtual Meeting // Twin Cities Wednesday // Shambala RD

("Allies" probably should be added, since there are meetings that are LGBTQIA + Allies currently. In the future, it's possible other affinities will do so too)

**Comment by unity1979** [comment]
Closing due to meeting list overhaul
