### ISSUE TITLE
-Request: Please Add 4 Topics to meeting topic attributes: Beginners, Family Support, Love & Lust, Mental Health

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#37]
Can we add these 4 topics? (Right now we are lumping them all into "Other". As of now, these topics have established meetings:)

- Beginners: 5 meetings
- Family Support: 2 meetings
- Love & Lust: 5 meetings
- Mental Health: 3 meetings

As seen:
![image](https://user-images.githubusercontent.com/70724023/153673744-2f825c46-1ad4-4e49-90b4-af82fa1b08fe.png)
![image](https://user-images.githubusercontent.com/70724023/153673967-f2c87d57-aa26-41e0-a4f6-b75d33045d84.png)
![image](https://user-images.githubusercontent.com/70724023/153674009-5457813c-0f54-420f-9337-9e440166a28c.png)
![image](https://user-images.githubusercontent.com/70724023/153673828-51eacb91-731e-4b31-b9ab-8f1ebf00de72.png)
@ https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit#gid=1394082114

**Comment by nutjob4life** [comment]
Added the 4 topics

**Comment by KrisRecoveryDharma** [comment]
Like
