### ISSUE TITLE
-Request: Can we default to List View for the meeting list? (instead of Map View)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#38]
Upon attempting to find a meeting, https://recovery-dharma.flywheelsites.com/meetings/find-a-meeting/
the meeting list goes to Map View for In-Person meetings around the world. 

Unfortunately, at the moment, I am uninterested in attending in-person meetings around the world. However, I am highly interested in attending online meetings worldwide! :) so I simply need to click on List View to get to that. 

As simple as that is, Defaulting to List View would help many others, if more are seeking virtual meetings than in-person. 

Request: Can we default to List View (instead of Map View)?

**Comment by nutjob4life** [comment]
As nifty as the map view is, we're still in a pandemic. I think I'd agree.

@KrisRecoveryDharma what do you think?

**Comment by KrisRecoveryDharma** [comment]
I agree!

**Comment by unity1979** [comment]
Closing due to meeting list overhaul
