### ISSUE TITLE
Language "Abington RD" should be removed from language options

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#39]
The language "Abington RD" is seen in

Meetings List:
![image](https://user-images.githubusercontent.com/70724023/153683799-22ca5cab-6df7-4720-bd95-2c207a8c9799.png)

Create a meeting:
![image](https://user-images.githubusercontent.com/70724023/153683824-7e1c99eb-c927-455d-8c30-c3cbd167aeeb.png)

Expected behavior:
It should not be a language. :)

**Comment by nutjob4life** [comment]
Deleted
