### ISSUE TITLE
Prune "old" meetings list of <2021 meetings. (Tag meetings for removal if not heard from since 2020)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/Meetings#43]
Let's cleanup our old meeting list, since we're still going to use it for an unknown period of time. 

Reason:
People have reported numerous online & inperson meetings that are no longer happening. We have 90 meetings that have not been updated since 2020. The user experience of attempting to attend an in-person meeting, where no meeting is happening causes suffering. We can be skillful by keeping up-to-date each year.

Recommended tasks:
1) Flag all meetings that haven't been updated since 2020.
2) Email each meeting "owner" that their meeting is defaulting to be Tagged for removal (in 1? week), due to non-update since 2020 and in attempt to keep meeting list fresh every year. They can reply to the email to let us know the status, if it shouldn't be removed.
3) In 1(?) week, remove any meetings still Tagged for removal.

@KrisRecoveryDharma / @Lacey-boop, please let me know if you think this is idea works. Or if you have any thoughts or questions. I will await for your response.

**Comment by KrisRecoveryDharma** [comment]
I like this idea.
Adjustments:
* Let's make it two weeks with a second email and a social media splash going out. 
* We'll need to go through our RDG review process to approve the content of the mass emails and social media posts. 

Kris

**Comment by unity1979** [comment]
@KrisRecoveryDharma Here is a draft email. Can you review and make edits for this?:


Dear Admirable RD Meeting Organizer(s),

With the new RDG website launch, now is a good time to ensure the meeting list is also refreshed. It’s been a long while since COVID began. Our official 400+ meeting list has been a huge collective effort—and we *need* your help. 

You’re receiving this email because:
1- Your email was associated with a meeting;
2- and that meeting hasn’t been updated since 2020.
3- So, we’re tagging that meeting for pruning (it will be removed after 2 weeks from today.)
4- We’re allowing a graceful 2-week period to reply/update your meeting for 2022 (Then it won’t get removed.)

(NOTE: MEETING INFO WILL BE DETAILED HERE. EACH EMAIL ADDRESS WILL RECEIVE ONLY THEIR CORRESPONDING MEETINGS.)

If your meeting is _no longer happening_—
You’re done! No action needed.

If your meeting is _still happening_—
1- Kindly verify the details of the meeting to ensure it’s 100% correct (Date/Time/Details/Email/ZoomInfo or In-Person Location). We’ve gone through great lengths to send an individual email for every single meeting, so please help. 
2- Reply to this to let us know what’s up. (Optional: if there’s a new organizer, forward this email to them!) 
3- That’s it--then we'll keep your meeting so people can keep finding it. 

This helps prevent people from showing up at meetings that are no longer happening. 

Thank you for being of service, and for serving as admirable examples of peer leadership in Recovery Dharma.

**Comment by KrisRecoveryDharma** [comment]
Thanks! I will send edits. Soon.  Generally good, tho!

Question:
Are the meetings visibly tagged on the spreadsheet?  Can organizers go
check it out?

So, the meeting is still active, but no one is monitoring the email we are
sending to.

**Comment by unity1979** [comment]
Re tagging: No, they will not be visibly tagged.

Yes, the meeting is still active according to anyone looking at the site. If nobody is monitoring the email we are sending to, then unfortunately the meeting will go down.

We can always add a column that says, "Tagged for removal, pls email ... if this meeting is still active!"

**Comment by KrisRecoveryDharma** [comment]
Yes, let's add a column.

Though maybe start with a gentler message:  Update Needed

Then we can use social media for the warning language.

**Comment by unity1979** [comment]
Perfect, it's on my task list then.

What do you mean by "use social media for the warning language?" I'm not
sure I understand the details

**Comment by KrisRecoveryDharma** [comment]
When we sent the email burst, we will also post messages on our accounts
for Instagram, twitter etc.  In this messages, we can be more detailed
about the plan to prune.

**Comment by unity1979** [comment]
@KrisRecoveryDharma Sounds good. Should we move forward with emails (coming from meetings@recoverydharma.org?) 

BTW I added the appropriate column header with "Update Needed?" with the example data in the Japan timezone at http://japan.rd.guide - it says 

"Update Needed. Last: 4/21/2020" for example
![image](https://user-images.githubusercontent.com/70724023/159211467-83f03d08-8879-46cc-839a-643567117592.png)

**Comment by KrisRecoveryDharma** [comment]
Thank you for creating that. It is very helpful.

I was pulled to other tasks last past week. My next step for this project
is to add a few edits to the draft of the email.

Kris

**Comment by unity1979** [comment]
This is completed. Report:

115 Meetings were marked for pruning
55 Meetings were pruned (Hidden - No response)

60 Meetings received a response for either:
1) Still active; or
2) No longer active, please remove

Huzzah! Thanks for your help Kris!
