### ISSUE TITLE
Update links to time Converted tabs

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Meetings#5]
Update the links to the Time Converted and the In Person tabs so that 
1) Only that tab shows
2) is embedded in our website. 

Thomas and Craig will generate and collect the URLs. 
Then they will work with Sean to update  the menu and the page, https://recoverydharma.org/meeting-list

**Comment by unity1979** [comment]
please note: Users will no longer be able to add comments if we use this solution.

@nutjob4life  Here are the links to be updated:

Tab/Time Zone Name | Published HTML Link:
-- | --
In Person | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1492891510&single=true
Hawaii | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=188599084&single=true
Pacific US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=496973103&single=true
Mountain US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1567715471&single=true
Central US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1870057131&single=true
Eastern US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1997228258&single=true
Atlantic | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=862403844&single=true
UK | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1799102808&single=true
Central Europe | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1971437393&single=true
Nepal | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=2113693318&single=true
Japan | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1497061528&single=true
Australia East | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1833391122&single=true
N Zealand | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=2131795796&single=true
Women / Nonbinary | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=5118134&single=true

**Comment by unity1979** [comment]
Should we open a new issue under /Website to update the website links to the above table?  re: https://recoverydharma.org/meeting-list ? @nutjob4life @KrisRecoveryDharma 

![image](https://user-images.githubusercontent.com/70724023/94396312-8360ce80-0116-11eb-8513-671db9dfe5f4.png)

**Comment by KrisRecoveryDharma** [comment]
Yes! Thank you!  I dropped that thread.
Please create a new issue on the Website GitHub.  Assign to both Seana and
Dirk.
