### ISSUE TITLE
Proposal:  On Meeting List page, Move "Stay Connected" and "About Process" up towards the top of the page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Meetings#8]
Hello Meeting List Team,

Currently on the Meeting page 
https://recoverydharma.org/meeting-list

The sections "Stay Connected" and "About the process" are at the bottom of the first column. 
There is a proposal to move it up towards the top by putting it at the bottom of the second, (shorter) Column. 
So, Stay Connected would be listed directly under "Start a New Online Meeting."

Please let me know if you support or have any concerns.  
I'll send a request to sean if there is support. 

Kris

**Comment by unity1979** [comment]
Sean has has addressed this and it looks fabulous 💖 (Please re-open issue if I am seeing unclearly)

![image](https://user-images.githubusercontent.com/70724023/94183810-d9ecb500-fe57-11ea-9e5a-5bcc839585ab.png)
